In [2]:
import numpy as np

In [6]:
e = np.arange(0, 10, 2)
e

array([0, 2, 4, 6, 8])

In [7]:
f = np.linspace(0, 1, 5)
f

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
g = np.random.rand(3, 2)
g

array([[0.71896657, 0.7219228 ],
       [0.85062181, 0.70472943],
       [0.97878207, 0.15301824]])